{"name": "故障告警导出-大于5万条", "status": "passed", "attachments": [{"name": "log", "source": "e072946a-a254-4aa9-bb31-89c9d23ef4c2-attachment.txt", "type": "text/plain"}], "start": 1692256538083, "stop": 1692256553096, "uuid": "3a04e6fa-1656-4d48-8753-69ac58177f31", "historyId": "2b7e77ac4a735b3ca8f633e8ccc15fd3", "testCaseId": "22f196651ae024df4cebd194ab2f9091", "fullName": "opsPC.test_alarm#test_alarm_fault_export_001", "labels": [{"name": "feature", "value": "运维管理平台"}, {"name": "story", "value": "应急处置"}, {"name": "parentSuite", "value": "opsPC"}, {"name": "suite", "value": "test_alarm"}, {"name": "host", "value": "cale"}, {"name": "thread", "value": "19796-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "opsPC.test_alarm"}]}