{"name": "故障告警导出-大于5万条", "status": "passed", "attachments": [{"name": "log", "source": "c0213b2a-7260-4dd7-9bfa-6b443bea5a48-attachment.txt", "type": "text/plain"}], "start": 1692260188719, "stop": 1692260206187, "uuid": "e70cba88-959a-4d5d-963a-94657b8ca84e", "historyId": "2b7e77ac4a735b3ca8f633e8ccc15fd3", "testCaseId": "22f196651ae024df4cebd194ab2f9091", "fullName": "opsPC.test_alarm#test_alarm_fault_export_001", "labels": [{"name": "feature", "value": "运维管理平台"}, {"name": "story", "value": "应急处置"}, {"name": "parentSuite", "value": "opsPC"}, {"name": "suite", "value": "test_alarm"}, {"name": "host", "value": "cale"}, {"name": "thread", "value": "16680-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "opsPC.test_alarm"}]}