{"name": "困人处置列表-误报", "status": "passed", "attachments": [{"name": "log", "source": "2a1f2524-556d-418b-b67b-b5e722399d3e-attachment.txt", "type": "text/plain"}], "start": 1692260235657, "stop": 1692260235883, "uuid": "d3265e9d-d3cf-4a5b-b0ff-6d1d4f90a494", "historyId": "b6df9803d2bc4b21784f5a63eb51f738", "testCaseId": "dc6b56f404a99f8f9a0366f36753c0b5", "fullName": "opsPC.test_emergency#test_device_error_trapped_list_004", "labels": [{"name": "feature", "value": "运维管理平台"}, {"name": "story", "value": "应急处置"}, {"name": "parentSuite", "value": "opsPC"}, {"name": "suite", "value": "test_emergency"}, {"name": "host", "value": "cale"}, {"name": "thread", "value": "16680-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "opsPC.test_emergency"}]}