{"name": "故障告警导出-大于5万条", "status": "passed", "attachments": [{"name": "log", "source": "1c6fe3cd-fe54-417f-b6ab-64a4b3067d8c-attachment.txt", "type": "text/plain"}], "start": 1692178343108, "stop": 1692178361798, "uuid": "03638ddd-6bfa-4a5f-8c18-10205211e22d", "historyId": "2b7e77ac4a735b3ca8f633e8ccc15fd3", "testCaseId": "22f196651ae024df4cebd194ab2f9091", "fullName": "opsPC.test_alarm#test_alarm_fault_export_001", "labels": [{"name": "feature", "value": "运维管理平台"}, {"name": "story", "value": "应急处置"}, {"name": "parentSuite", "value": "opsPC"}, {"name": "suite", "value": "test_alarm"}, {"name": "host", "value": "cale"}, {"name": "thread", "value": "13268-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "opsPC.test_alarm"}]}