{"name": "困人处置列表-误报", "status": "passed", "attachments": [{"name": "log", "source": "566fd2f0-f120-4aea-b178-0a8c0dd4490f-attachment.txt", "type": "text/plain"}], "start": 1690436276821, "stop": 1690436277061, "uuid": "80c1e570-4045-44f4-b960-9e3e7ac964e6", "historyId": "b6df9803d2bc4b21784f5a63eb51f738", "testCaseId": "dc6b56f404a99f8f9a0366f36753c0b5", "fullName": "opsPC.test_emergency#test_device_error_trapped_list_004", "labels": [{"name": "story", "value": "应急处置"}, {"name": "feature", "value": "运维管理平台"}, {"name": "parentSuite", "value": "opsPC"}, {"name": "suite", "value": "test_emergency"}, {"name": "host", "value": "cale"}, {"name": "thread", "value": "10244-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "opsPC.test_emergency"}]}