{"name": "故障告警导出-大于5万条", "status": "passed", "attachments": [{"name": "log", "source": "e6610d49-e80e-4794-862b-4af49492f76c-attachment.txt", "type": "text/plain"}], "start": 1690249572488, "stop": 1690249590500, "uuid": "f8a5b150-d456-4614-9f6f-c72a76598b27", "historyId": "2b7e77ac4a735b3ca8f633e8ccc15fd3", "testCaseId": "22f196651ae024df4cebd194ab2f9091", "fullName": "opsPC.test_alarm#test_alarm_fault_export_001", "labels": [{"name": "story", "value": "应急处置"}, {"name": "feature", "value": "运维管理平台"}, {"name": "parentSuite", "value": "opsPC"}, {"name": "suite", "value": "test_alarm"}, {"name": "host", "value": "cale"}, {"name": "thread", "value": "4716-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "opsPC.test_alarm"}]}